services:
  atcoder:
    container_name: atcoder
    build:
      context: ./docker
    tty: true
    volumes:
      - ./work:/work
      - ./docker/ac-library:/work/ac-library
      - ./docker/cpp-dump:/work/cpp-dump